name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: npm-publish
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write # needed for npm trusted publishing (OIDC)
  actions: read

jobs:
  publish-release:
    name: Publish release to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: npm

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Clone matterbridge repo branch main
        run: git clone --depth 1 --single-branch --no-tags -b main
          https://github.com/Luligu/matterbridge.git ../matterbridge

      - name: Install matterbridge dependencies
        working-directory: ../matterbridge
        run: npm ci --no-fund --no-audit

      - name: Build matterbridge
        working-directory: ../matterbridge
        run: npm run build

      - name: Link matterbridge globally
        working-directory: ../matterbridge
        run: npm link --no-fund --no-audit

      - name: Install plugin dependencies
        run: npm ci --no-fund --no-audit

      - name: Link matterbridge in the project
        run: npm link matterbridge --no-fund --no-audit

      - name: Build the plugin
        run: npm run build

      - name: Lint the plugin
        run: npm run lint

      - name: Test the plugin
        run: npm run test -- --forceExit

      - name: Publish the plugin to npm with trusted publishing / OIDC
        run: npm publish
